export const ADD = Symbol('ADD')
export const DEL = Symbol('DEL')
export const COMPLETE = Symbol('COMPLETE')
export const BIND_INPUT = Symbol('BIND_INPUT')
export const DEL_INPUT = Symbol('DEL_INPUT')